import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PAITEC',
  description: 'Generated by PAITEC',
  openGraph: {
    images: [
      {
        url: '/og-imagem.png',
        width: 1200,
        height: 630,
        alt: 'PAITEC',
      },
    ],
  },
  icons: {
    icon: '/icone.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
